---
- name: Add value to tower inventory
  hosts: all
  gather_facts: no

  tasks:
    - name: Add tower inventory
      tower_inventory:
        name: "poc-a-patching"
        organization: "demo"
        state: present
        variables: "abc_variable: xyz_value"
        tower_host: "{{ lookup('env', 'VMWARE_HOST') | default('localhost') }}"
        tower_username: "{{ lookup('env', 'VMWARE_USER') }}"
        tower_password: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
      register: add_tower_inventory
      delegate_to: 127.0.0.1

    - name: read abc_variable from poc-a-patching inventory
      debug:
        var: add_tower_inventory