---
- name: Add value to tower inventory
  hosts: all
  gather_facts: no

  tasks:
    - name: test
      command: hostname
      delegate_to: 127.0.0.1

    - name: test
      command: whoami
      delegate_to: 127.0.0.1

    - name: Add tower inventory
      tower_inventory:
        name: "poc-b-patching"
        organization: "Demo"
        state: present
        tower_config_file: "~/tower_cli.cfg"
      delegate_to: 127.0.0.1