---
- name: Add value to tower inventory
  hosts: all
  gather_facts: no

  tasks:
    - name: hostname
      command: hostname
      register: hostname_output
      delegate_to: 127.0.0.1

    - debug:
        var: hostname_output

    - name: whoami
      command: whoami
      register: whoami_output
      delegate_to: 127.0.0.1

    - debug:
        var: whoami_output

    - name: inventory list
      shell: tower-cli inventory list
      register: inventory_output
      delegate_to: 127.0.0.1

    - debug:
        var: inventory_output

    - name: Add tower inventory
      tower_inventory:
        name: "poc-b-patching"
        organization: "Demo"
        state: present
        tower_config_file: "~/tower_cli.cfg"
      delegate_to: 127.0.0.1