---
- name: Add value to tower inventory
  hosts: all
  gather_facts: no

  tasks:
    - name: Add tower inventory
      tower_inventory:
        name: "poc-a-patching"
        organization: "Demo"
        state: present
        variables: "test=value"
        tower_config_file: "/etc/tower/tower_cli.cfg"
      delegate_to: localhost

    - name: test
      command: hostname
      delegate_to: 127.0.0.1