- hosts: localhost
  become: no

  tasks:
  - name: Create a resource group
    azure_rm_resourcegroup:
      name: Testing
      location: southcentralus
      tags:
        testing: testing
        delete: never
    ignore_errors: yes

  - name: Create storage account
    azure_rm_storageaccount:
      resource_group: Testing
      name: oratestaccount001
      account_type: Standard_LRS

  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: Testing
      name: oratestvn001
      address_prefixes: "10.10.0.0/16"

  - name: Add subnet
    azure_rm_subnet:
      resource_group: Testing
      name: orasubnet001
      address_prefix: "10.10.0.0/24"
      virtual_network: oratestvn001

  - name: Create public ip
    azure_rm_publicipaddress:
      resource_group: Testing
      allocation_method: Static
      name: orapublicip001

  - name: Create security group that allows SSH
    azure_rm_securitygroup:
      resource_group: Testing
      name: orasecgroup001
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 101
          direction: Inbound

  - name: Create NIC
    azure_rm_networkinterface:
      resource_group: Testing
      name: oratestnic001
      virtual_network: oratestvn001
      subnet: orasubnet001
      public_ip_name: orapublicip001
      security_group: orasecgroup001

  - name: Create virtual machine
    azure_rm_virtualmachine:
      resource_group: Testing
      name: oratestvm001
      vm_size: Standard_D1
      storage_account: oratestaccount001
      storage_container: oratestvm001
      storage_blob: oratestvm001.vhd
      admin_username: oatakan
      admin_password: Password!
      network_interfaces: oratestnic001
      image:
        offer: CentOS
        publisher: OpenLogic
        sku: '7.1'
        version: latest