---
- name: check os information
  hosts: all
  tasks:
  - name: current OS version information
    debug:
      var: os_info
    vars:
      os_info:
        distribution: "{{ ansible_distribution }}"
        distribution_major_version: "{{ ansible_distribution_major_version }}"
        distribution_release: "{{ ansible_distribution_release }}"
        distribution_version: "{{ ansible_distribution_version }}"