- hosts: tag_role_oracle_single_instance_v2:&tag_app_oracle_si_demo
  become: yes
  roles:
  - ansible-oracle/roles/common
  - ansible-oracle/roles/orahost
  - ansible-oracle/roles/oraswdb-install
  - ansible-oracle/roles/oradb-create
  - custom-post-install

  tasks:
  - name: run my shell script after oracle
    command: hostname

  - name: run my shell script after oracle
    command: hostname