- hosts: oracle_rac_data_center_hosts
  become: yes
  serial: 1
  var:
    ORACLE_HOME: /oracle/home
    gold_image_file: /mnt/some_file.tar.gz

  pre_tasks:
    - name: find all instances
      command: find_instance_command
      register: database_instances

    - name: bring down all oracle instances
      command: bring_down_instance "{{ item }}"
      with_items: "{{ database_instances.stdout }}"

    - name: remove softlink to HOME
      command: rm {{ ORACLE_HOME }}

  tasks:
    - name: untar gold image
      unarchive:
        src: "{{ gold_image_file }}"
        dst: /tmp

    - name: run installer command
      command: /tmp/run_installer {{ ORACLE_HOME }}

  post_tasks:
    - name: run cat bundle
      command: cat_bundle

    - name: is it running?
      command: ps -ef  |gaeiflaks
      register: oracle_process

    - name: debug
      debug:
        msg: "update succesful"
      when: "{{ oracle_process | success }}
