- hosts: all
  vars:
    phpipam_install_from_git: true
    phpipam_install_git_version: 'HEAD'
    apache2_config: true
    apache2_config_php: true
    apache2_config_virtual_hosts: false
    apache2_default_port: 80
    apache2_install_php_sqlite: true
    apache2_install_php: true

  pre_tasks:
    - name: install epel
      yum:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
        state: present
    - name: install prereq packages
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - git
  roles:
    - mrlesmithjr.apache2
    - ansible-mariadb-mysql
    - mrlesmithjr.phpipam