- hosts: all
  vars:
    phpipam_install_from_git: true
    phpipam_install_git_version: 'HEAD'
  pre_tasks:
    - name: install epel
      yum:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
        state: present
    - name: install prereq packages
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - git
  roles:
    - mrlesmithjr.apache2
    - ansible-mariadb-mysql
    - mrlesmithjr.phpipam