- hosts: all
  vars:
    phpipam_install_from_git: false
    phpipam_version: phpipam-1.1.010
    phpipam_download: 'https://downloads.sourceforge.net/project/phpipam/phpipam-1.1.010.tar?r=https%3A%2F%2Fsourceforge.net%2Fprojects%2Fphpipam%2Ffiles%2F%3Fsource%3Dnavbar&ts=1508884410&use_mirror=cfhcable'
    phpipam_download_file: '{{ phpipam_version }}.tar'
    #phpipam_install_git_version: 'HEAD'
    apache2_config: true
    apache2_config_php: true
    apache2_config_virtual_hosts: false
    apache2_default_port: 80
    apache2_install_php_sqlite: true
    apache2_install_php: true

  pre_tasks:
    - name: install epel
      yum:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
        state: present
    - name: install prereq packages
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - git
        - php-mbstring
        - php-gd
  roles:
    - mrlesmithjr.apache2
    - ansible-mariadb-mysql
    - mrlesmithjr.phpipam

  post_tasks:
    - name: update admin password
      mysql_user:
        name: Admin
        password: ipamadmin
        priv: phpipam.*:ALL
        state: present