- hosts: tag_role_dbservers:&tag_app_rolling_app
  become: yes
  become_user: root
  roles:
  - geerlingguy.mysql

- hosts: tag_role_webservers:&tag_app_rolling_app
  become: yes
  become_user: root
  roles:
  - geerlingguy.nginx

- hosts: tag_role_lbservers:&tag_app_rolling_app
  become: yes
  become_user: root
  vars:
    http_port: "{{':'}}80"
  pre_tasks:
  - debug: var=http_port
  - name: Populate backend servers
    set_fact:
      haproxy_backend_serverss: "{{ haproxy_backend_servers|default([]) + [ {'name': hostvars[item].ansible_hostname, 'address': hostvars[item].ansible_default_ipv4.address ] }}"
    with_items: "{{ groups.tag_role_webservers }}"
  - debug: var=haproxy_backend_servers2
  roles:
  - geerlingguy.haproxy
