- hosts: tag_role_dbservers:&tag_app_rolling_app
  become: yes
  become_user: root
  roles:
  - geerlingguy.mysql

- hosts: tag_role_webservers:&tag_app_rolling_app
  become: yes
  become_user: root
  roles:
  - geerlingguy.nginx

- hosts: tag_role_lbservers:&tag_app_rolling_app
  become: yes
  become_user: root
  vars:
    http_port: "{{':'}}80"
    haproxy_backend_servers:
    - name: web1
      address: "{{groups['tag_role_webservers'][0]}}{{http_port}}"
    - name: web2
      address: "{{groups['tag_role_webservers'][1]}}{{http_port}}"
  pre_tasks:
  - debug: var=haproxy_backend_servers
  - name: Populate backend servers
    set_fact:
      haproxy_backend_servers2: "{{ haproxy_backend_servers2|default([]) + [ {'name': hostvars[item].ansible_hostname, 'address': hostvars[item].ansible_hostname ] }}"
    with_items: "{{ groups.tag_role_webservers }}"
  - debug: var=haproxy_backend_servers2
  roles:
  - geerlingguy.haproxy
