- hosts: localhost
  become: no
  vars:
    ec2_exact_count: 0
  tasks:
    - name: get ec2 information
      ec2_remote_facts:
        region: "{{ ec2_region }}"
        filters:
          vpc-id: "{{ ec2_vpc_id }}"
          "tag:app": rolling_app
      register: ec2_instances

    - debug:
        var: item.id
      with_items: "{{ ec2_instances.instances }}"

#    - name: terminate instances
#      ec2:
#        state: 'absent'
#        instance_ids: '{{ ec2.instance_ids }}'