- hosts: localhost
  become: no
  vars:
    ec2_exact_count: 0
  tasks:
    - name: get ec2 information
      ec2_remote_facts:
        region: "{{ ec2_region }}"
        filters:
          vpc-id: "{{ ec2_vpc_id }}"
          "tag:role": dbservers
          "tag:role": webservers
          "tag:role": lbservers
          "tag:app": dbservers
      register: ec2_instances

    - debug:
        msg: "{{ ec2_instances }}"