---
- name: Add value to tower inventory
  hosts: all
  gather_facts: no
  vars:
    tower_hostname: "{{ lookup('env', 'VMWARE_HOST') | default('localhost') }}"
    tower_username: "{{ lookup('env', 'VMWARE_USER') }}"
    tower_password: "{{ lookup('env', 'VMWARE_PASSWORD') }}"

  roles:
     - role: tower_group_write_variables
       inventory_name: demo-update-group
       group_name: child-group
       group_variables:
         some_parameter: some_value
         another_parameter: another_value

  post_tasks:
    - name: debug variables from main playbook
      debug:
        var: group_variables
      when: group_variables is defined