- name: Create User Group
  group:
    name: "{{ username }}"
    state: present
  tags:
    - user_accounts
    - users

- name: Create User Account
  user:
    createhome: yes
    group: "{{ username }}"
    name: "{{ username }}"
    shell: /bin/bash
    state: present
    password: "{{ admin_password_hash }}"
  tags:
    - user_accounts
    - users

- name: Configure sshd and sudoers
  lineinfile:
    dest: "{{ item.dest }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: "{{ item.state | default('present') }}"
    validate: "{{ item.validate | default(omit) }}"
    backup: no
  with_items: "{{ common_node_config_options }}"
  notify: restart ssh